apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: dmlzaG51YWxsYW1wYWxsaQ==  # Base64 encoded value of your usrname
  password: MTEyMmFtYWdl  # Base64 encoded value of your password

